# Generated by Django 3.1 on 2020-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='original_image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='resized_image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
