# Generated by Django 3.1 on 2020-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0003_auto_20200807_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image_name',
            field=models.CharField(max_length=128),
        ),
    ]
